fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "akramexleom@email.com"
        sender_name: "Sender Name"
    service:
      mailer: 'Symfony\Component\Mailer\MailerInterface'