twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        max_jobs_on_homepage: '%max_jobs_on_homepage%'
        jobs_web_directory: '%jobs_web_directory%'
        locales: '%locales%'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'

when@test:
    twig:
        strict_variables: true
        
