controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        ar: '/ar'
        fr: '/fr'

api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api/v1/

kernel:
    resource: ../../src/Kernel.php
    type: annotation